name: CD
on:
  push:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploying to DEMO"
        uses: appleboy/ssh-action@master
        with:
          host: "167.172.95.149"
          username: ${{ secrets.USERNAME_DEMO }}
          PASSWORD: ${{ secrets.PASSWORD_DEMO }}
          port: 22
          script: |
            cd public_html
            git checkout production
            git pull origin production
            /usr/local/lsws/lsphp81/bin/php /usr/local/bin/composer install --ignore-platform-reqs
            /usr/local/lsws/lsphp81/bin/php ./artisan migrate
