name: CD
on:
  push:
    branches: [ production ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploying to ITQAN"
        uses: appleboy/ssh-action@master
        with:
          host: '178.128.25.125'
          username: ${{ secrets.USERNAME_ITQAN }}
          PASSWORD: ${{ secrets.PASSWORD_ITQAN }}
          port: 22
          script: |
            cd public_html/
            git pull origin production
            
