name: CD
on:
  push:
    branches: [ production ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploying to smanaga"
        uses: appleboy/ssh-action@master
        with:
          host: '146.190.81.35'
          username: ${{ secrets.USERNAME_littlesunschool }}
          PASSWORD: ${{ secrets.PASSWORD_littlesunschool }}
          port: 22
          script: |
            cd public_html/
            git pull git@github.com:Fresto-Code/aristoteles-sim.git production
