name: CD
on:
  push:
    branches: [ production ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "209.97.170.217"
        uses: appleboy/ssh-action@master
        with:
          host: '209.97.170.217'
          username: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/magazine.afresto.id/public_html/
            git pull https://github.com/Fresto-Code/aristoteles-sim 'production'
            php artisan migrate
            php artisan optimize
            composer install
