name: CD
on:
  push:
    branches: [ production ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "209.97.170.217"
        uses: appleboy/ssh-action@master
        with:
          host: '209.97.170.217'
          username: ${{ secrets.USERNAME_SMANAGA }}
          PASSWORD: ${{ secrets.PASSWORD_SMANAGA }}
          port: 22
          script: |
            cd public_html/
            git pull https://github.com/Fresto-Code/aristoteles-sim 'production'
            git reset --hard
