name: CD
on:
  push:
    branches: [ production ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploying to emagazine.smknjatengsmg.id"
        uses: appleboy/ssh-action@master
        with:
          host: '188.166.227.1'
          username: ${{ secrets.USERNAME_SMKNJATENGSMG }}
          PASSWORD: ${{ secrets.PASSWORD_SMKNJATENGSMG }}
          port: 22
          script: |
            cd public_html
            git checkout production
            git pull origin production
            composer install --ignore-platform-reqs
            php artisan optimize
            php artisan migrate
            composer install --ignore-platform-reqs